### ISSUE TITLE
student/teacher experiments

### ISSUE THREAD

**Issue by DaveDe** [artemyk/ibsgd#10]
Hello,

I've been trying to reproduce the results of the student-teacher experiments in sections 3 and 5, however my MSE and MI calculations are not matching the results in figures 3 and 6. I followed the description in the paper as closely as possible, and am wondering if I'm missing any details, such as how you are initializing the weights in the student network? If it's possible to post the code for these experiments, or provide any additional implementation details I might be missing, that would be very helpful.

Thanks

**Comment by artemyk** [comment]
@DaveDe You might want to try emailing Andrew Saxe with your questions, he might know the details of those experiments.

**Comment by DaveDe** [comment]
Thanks, will do.
