### ISSUE TITLE
simplebinmi has a error i think

### ISSUE THREAD

**Issue by PixelsForest** [artemyk/ibsgd#7]
the 18th line:
for xval in unique_inverse_x:
should be 
for xval in np.unique(unique_inverse_x):

**Comment by artemyk** [comment]
Hi @WOOOOOOOOOOOOOO . Could you explain why you think this is an error?

**Comment by PixelsForest** [comment]
i think this should be summing over different x a X can be, but this code is summing over all the samples.
e.g. unique_inverse_x is like [0, 0, 1, 1, 2] means three different x and five samples. calculating entropy is summing over 0 1 2( the possible x), not 0 0 1 1 2.
Also i think it's an error because it sometimes gives me minus MI.

**Comment by PixelsForest** [comment]
Besides, may I ask why variance=0.1 was chosen in "On the IB theory of deep learning"?
The H_KL upper bound, which is used to calculate MI, has a 0.5*ln|sigma| so it varies. You cannot even guarantee it's positive if variance is close to zero.

**Comment by artemyk** [comment]
Thanks for pointing out the error in funtion `bin_calc_information ` in `simplebinmi.py`.  I just pushed a fix to the code.  Note that this function was not used to generate the plots in the paper, so results there are not affected.

Regarding the choice of variance=0.1 : this was chosen to give results that are qualitatively similar to the other MI estimation strategy (using binning). MI is always positive, no matter the variance.  Our upper bound is also therefore always positive.
