### ISSUE TITLE
an error in kde.py

### ISSUE THREAD

**Issue by PixelsForest** [artemyk/ibsgd#8]
line 41:
return (dims/2.0)*(np.log(2*np.pi*var) + 1)
should be:
return (1/2.0)*(np.log(var)+dims*np.log(2*np.pi) + dims)
i think this is what equation(14) means in paper"estimating mixture entropy..."

**Comment by artemyk** [comment]
The code is correct as-is.

First, note that 
``(dims/2.0)(np.log(2*np.pi*var) + 1)`` == ``(1/2.0)(dims*np.log(var) + dims*np.log(2*np.pi) + dims)``

Now, Eq. 14 in the paper ''Estimating Mixture Entropy with Pairwise Distances'' refers to the determinant of the covariance matrix. In this work, we assume the covariance matrix has the form `var*np.eye(dims)`. The determinant of such a matrix is `var**dims` , and its logarithm is `dims * np.log(var)`.

**Comment by PixelsForest** [comment]
yeah sorry it's my fault
